Repository MagnoCarta/Shiritori, pull requests merged in 2020-09, with the labels that each got.

#4 Signin
  Xiritori.xcodeproj/project.pbxproj
  Xiritori/Controller/LoginController.swift
  Xiritori/Controller/SigninController.swift
  Xiritori/Controller/ViewController.swift
  Xiritori/Extension/LoginViewExtension.swift
  Xiritori/Extension/SigninViewExtension.swift
  Xiritori/Extension/UIVIewExtension.swift
  Xiritori/Info.plist
  Xiritori/SceneDelegate.swift
  Xiritori/View/Assets.xcassets/test.imageset/Contents.json
  Xiritori/View/Assets.xcassets/test.imageset/test.png
  Xiritori/View/Components/Separator.swift
  Xiritori/View/LoginView.swift
  Xiritori/View/SigninView.swift
Labels: bug, enhancement, help wanted

#5 Add friend
  Xiritori.xcodeproj/project.pbxproj
  Xiritori/Controller/AddFriendController.swift
  Xiritori/Controller/FriendsController.swift
  Xiritori/Extension/ColorExt.swift
  Xiritori/Extension/UISearchBarExtension.swift
  Xiritori/SceneDelegate.swift
  Xiritori/View/AddFriend.swift
  Xiritori/View/Assets.xcassets/bart.imageset/Contents.json
  Xiritori/View/Assets.xcassets/bart.imageset/bart.jpeg
  Xiritori/View/FriendsTableView.swift
  Xiritori/View/FriendsTableViewCell.swift
  Xiritori/View/FriendsView.swift
Labels: bug, enhancement, help wanted

#2 Chat game
  Xiritori.xcodeproj/project.pbxproj
  Xiritori/Comfortaa.ttf
  Xiritori/Controller/ChatGameController.swift
  Xiritori/Extension/ColorExtension.swift
  Xiritori/Extension/Extension.swift
  Xiritori/Info.plist
  Xiritori/Model/Model.swift
  Xiritori/SceneDelegate.swift
  Xiritori/View/Base.lproj/LaunchScreen.storyboard
  Xiritori/View/ChatCell.swift
  Xiritori/View/ChatGame.swift
Labels: bug, enhancement, good first issue

#3 Tela Inicial
  .swiftlint.yml
  MyMessyHandwriting.ttf
  Xiritori.xcodeproj/project.pbxproj
  Xiritori/Controller/MainScreenController.swift
  Xiritori/Extension/ColorExtension2.swift
  Xiritori/Info.plist
  Xiritori/SceneDelegate.swift
  XiritoriTests/Info.plist
  XiritoriUITests/Info.plist
Labels: enhancement

#8 Tela de Modos de Jogo
  Xiritori.xcodeproj/project.pbxproj
  Xiritori/Controller/ChatGameController.swift
  Xiritori/Controller/MainScreenController.swift
  Xiritori/Extension/ChatGameExtension.swift
  Xiritori/Info.plist
  Xiritori/Model/Model.swift
  Xiritori/SceneDelegate.swift
  Xiritori/View/ChatGame.swift
  Xiritori/View/Components/ChatCell.swift
  Xiritori/View/MainScreenView.swift
  Xiritori/View/PlayScreenView.swift
Labels: enhancement

#9 Conserta falta do PlayScreenController
  Xiritori.xcodeproj/project.pbxproj
  Xiritori/Controller/PlayScreenController.swift
Labels: bug, help wanted

#12 Login cf
  Xiritori.xcodeproj/project.pbxproj
  Xiritori/Controller/AddFriendController.swift
  Xiritori/Controller/FriendsController.swift
  Xiritori/Controller/LoginController.swift
  Xiritori/Controller/SigninController.swift
  Xiritori/Extension/LoginViewExtension.swift
  Xiritori/Extension/SigninViewExtension.swift
  Xiritori/Extension/UISearchBarExtension.swift
  Xiritori/SceneDelegate.swift
  Xiritori/View/AddFriend.swift
  Xiritori/View/Components/FriendsTableView.swift
  Xiritori/View/Components/FriendsTableViewCell.swift
  Xiritori/View/Components/Separator.swift
  Xiritori/View/FriendsView.swift
  Xiritori/View/LoginView.swift
  Xiritori/View/SigninView.swift
Labels: enhancement

#10 Chat game
  Xiritori/Controller/ChatGameController.swift
  Xiritori/Controller/ViewController.swift
  Xiritori/Extension/ChatGameExtension.swift
  Xiritori/View/ChatGame.swift
Labels: enhancement

#11 Tela de Modo de Jogo
  Xiritori.xcodeproj/project.pbxproj
  Xiritori/AppDelegate.swift
  Xiritori/Controller/MainScreenController.swift
  Xiritori/Controller/PlayScreenController.swift
  Xiritori/Extension/UIViewExtension.swift
  Xiritori/View/Assets.xcassets/Textura.imageset/Contents.json
  Xiritori/View/Assets.xcassets/Textura.imageset/Textura de Fundo.png
  Xiritori/View/MainScreenView.swift
  Xiritori/View/PlayScreenView.swift
Labels: bug fix, enhancement

#14 Fluxo de Telas
  Xiritori/Controller/ChatGameController.swift
  Xiritori/Controller/EndMatchScreenController.swift
  Xiritori/Controller/LoginController.swift
  Xiritori/Controller/MainScreenController.swift
  Xiritori/Controller/PlayScreenController.swift
  Xiritori/SceneDelegate.swift
Labels: enhancement

#15 fix-bug-navbar-addbutton
  Xiritori/Controller/FriendsController.swift
Labels: bug

#16 Friends, Login Background
  Xiritori/View/AddFriend.swift
  Xiritori/View/FriendsView.swift
  Xiritori/View/LoginView.swift
  Xiritori/View/SigninView.swift
Labels: enhancement

#17 Animação de Botões
  Xiritori/Controller/MainScreenController.swift
  Xiritori/Controller/PlayScreenController.swift
Labels: enhancement

#21 Settings
  MyPlaygroundGetWords/Info.plist
  MyPlaygroundGetWords/MyPlaygroundGetWords.h
  MyPlaygroundGetWordsTests/Info.plist
  MyPlaygroundGetWordsTests/MyPlaygroundGetWordsTests.swift
  Xiritori.xcodeproj/project.pbxproj
  Xiritori/Controller/ChatGameController.swift
  Xiritori/Controller/MainScreenController.swift
  Xiritori/Controller/SettingsViewController.swift
  Xiritori/Extension/ChatGameExtension.swift
  Xiritori/Extension/SettingsExtension.swift
  Xiritori/Model/Model.swift
  Xiritori/Model/getWords.swift
  Xiritori/View/Assets.xcassets/GalinhaSozinha.imageset/Contents.json
  Xiritori/View/Assets.xcassets/GalinhaSozinha.imageset/GalinhaSozinha.png
  Xiritori/View/Assets.xcassets/Galinhatopper.imageset/Contents.json
  Xiritori/View/Assets.xcassets/Galinhatopper.imageset/Galinhatopper.png
  Xiritori/View/Assets.xcassets/galinhatopper2.imageset/Contents.json
  Xiritori/View/Assets.xcassets/galinhatopper2.imageset/galinhatopper2 (1).png
  Xiritori/View/ChatGame.swift
  Xiritori/View/Components/ChatCell.swift
  Xiritori/View/Components/SettingsCell.swift
  Xiritori/View/SettingsView.swift
Labels: enhancement

#22 User signin
  Xiritori.xcodeproj/project.pbxproj
  Xiritori/Controller/LoginController.swift
  Xiritori/Controller/SigninController.swift
  Xiritori/Model/ErrorBody.swift
  Xiritori/Model/Session.swift
  Xiritori/Model/User.swift
  Xiritori/Repository/UserRepository.swift
  Xiritori/Service/Router.swift
  Xiritori/Service/Service.swift
  Xiritori/Service/ServiceError.swift
  Xiritori/View/SigninView.swift
Labels: enhancement

#24 User signin
  Xiritori/Controller/LoginController.swift
  Xiritori/Controller/SigninController.swift
Labels: bug, enhancement

#23 Assets para títulos de telas
  Xiritori/Info.plist
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Contents.json
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-1024.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-20.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-20@2x.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-20@3x.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-29.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-29@2x.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-29@3x.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-40.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-40@2x.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-40@3x.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-60@2x.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-60@3x.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-76.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-76@2x.png
  Xiritori/View/Assets.xcassets/AppIcon.appiconset/Logo v3-83.5@2x.png
  Xiritori/View/Assets.xcassets/Flag.imageset/Contents.json
  Xiritori/View/Assets.xcassets/Flag.imageset/Flag.png
  Xiritori/View/Assets.xcassets/Flag.imageset/Flag@2x.png
  Xiritori/View/Assets.xcassets/Flag.imageset/Flag@3x.png
  Xiritori/View/Assets.xcassets/Title.imageset/Contents.json
  Xiritori/View/Assets.xcassets/Title.imageset/Title.png
  Xiritori/View/Assets.xcassets/Title.imageset/Title@2x.png
  Xiritori/View/Assets.xcassets/Title.imageset/Title@3x.png
  Xiritori/View/MainScreenView.swift
  Xiritori/View/PlayScreenView.swift
Labels: enhancement
